### ISSUE TITLE
Add URL other than GA portal

### ISSUE THREAD

**Issue by tsubasaxZZZ** [horihiro/Azure-portal-plus-ChromeExtension#1]
How about adding "ms.portal.azure.com" and "preview.portal.azure.com" to match URL list?

**Comment by horihiro** [comment]
Thanks @tsubasaxZZZ , they can be added.
But I cannot check if the extension works properly on `ms.portal.azure.com` because my browser is redirected to `portal.azure.com` when accesing `ms.portal.azure.com`.
On the other hand, `preview.portal.azure.com` can be opened on even my env. It should be added on next release.

**Comment by tsubasaxZZZ** [comment]
Thank you for your interest. Of course, I'll test for the ms domain after the next release.

**Comment by horihiro** [comment]
New version (0.0.2) is released.

**Comment by tsubasaxZZZ** [comment]
I have confirmed that each feature is working correctly.
Thank you!
